# Generated by Django 5.2.3 on 2025-07-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('country', models.TextField(max_length=250)),
                ('currency', models.IntegerField()),
            ],
        ),
    ]
