# Generated by Django 5.2.3 on 2025-07-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(max_length=100),
        ),
    ]
