# Generated by Django 5.2.3 on 2025-07-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_priceusd_crypto_price_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='crypto',
            field=models.ManyToManyField(to='main_app.crypto'),
        ),
    ]
